### ISSUE TITLE
owie help this is not python mommy help

### ISSUE THREAD

**Issue by jonasgeist123** [greybaron/stuwecrawler-rust#1]
i recomend writing a tkinter API from rust to python. Please pubsish this as a new repo and use this api. 

ALSO this needs to be hosted somewhere

mr jones

**Comment by greybaron** [comment]
Dear Mr. @jonasgeist123,

Regarding your concerns:


> writing a tkinter API from rust to python
No.

> this needs to be hosted somewhere
it is, Telegram @ba_mensa_bot.

Heave a great rest of the week,
Gerhardt

**Comment by jonasgeist123** [comment]
NO this must be hosted on a website TELEGRAM is not acceptable. Please host on web 😡😡😡😡😁😁😁😁
